---
title: "Partial residuals and regsubsets"
author: "Are"
date: "2023-06-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r OLD}
# full_raw_data <- read_excel("data/20230424_nordsjoen_stepan.xlsx", skip = 1) %>%
#     clean_names() %>%
#     select(species, year, hel_vekt_g, length_cm, fettinnhold_percent, matches("w_w"), lsi_percent, alder_y) %>%
#     drop_na(species, year) %>%
#     mutate(across(.cols = matches("w_w"), .fn = ~ log10(as.numeric(.x) + 1))) %>%
#       mutate(across(.cols = matches("length_cm"), .fn = ~ log10(as.numeric(.x)))) %>%
#   mutate(across(.cols = matches("fettinnhold_percent|year|hel_vekt_g|alder_y|lsi_percent"), .fn = ~ as.numeric(.x))) %>% 
#     rename_with(
#       ~ str_replace_all(.x, c(
#         "w_w" = "ww",
#         "^s" = "",
#         "fettinnhold_percent" = "fat_pc",
#         "hel_vekt_g" = "weight",
#         "lsi_percent" = "lsi_pc",
#         "alder_y" = "age"
#       )) %>%
#         str_to_lower(),
#       .cols = !matches("species")
#     ) %>%
#     # remove obs with no pop data
#     filter(if_any(matches("ww"), ~ !is.na(.x))) %>%
#     pivot_longer(cols = matches("ww"), names_to = "variable", values_to = "value")
# 
# 
# # full linear regression model
# lm_y_l_f_w_s_a <- function(in_dat) {
#   lm(
#     data = in_dat, formula = value ~ year + length_cm + fat_pc + weight + lsi_pc + age,
#     na.action = na.exclude
#   )
# }
# 
# lm_y_l_f_w_s <- function(in_dat) {
#   lm(
#     data = in_dat, formula = value ~ year + length_cm + fat_pc + weight + lsi_pc,
#     na.action = na.exclude
#   )
# }    
#     
#     
# lm_y_l_f_w <- function(in_dat) {
#   lm(
#     data = in_dat, formula = value ~ year + length_cm + fat_pc + weight,
#     na.action = na.exclude
#   )
# }
# lm_y_l_f <- function(in_dat) {
#   lm(
#     data = in_dat, formula = value ~ year + length_cm + fat_pc ,
#     na.action = na.exclude
#   )
# }
# lm_y_l <- function(in_dat) {
#   lm(
#     data = in_dat, formula = value ~ year + length_cm,
#     na.action = na.exclude
#   )
# }
# lm_y <- function(in_dat) {
#   lm(
#     data = in_dat, formula = value ~ year,
#     na.action = na.exclude
#   )
# }
# 
# # conditional manual
# selection_man <- full_raw_data %>%
#   ungroup() %>%
#   group_by(species, variable) %>%
#   drop_na(value) %>% 
#   nest() %>% 
#   # apply m1_y_l_f_w_s_a and calculate medians of covariates
#   mutate(
#     m_y_l_f_w_s_a = map(data, lm_y_l_f_w_s_a),
#     m_y_l_f_w_s = map(data, lm_y_l_f_w_s),
#     m_y_l_f_w = map(data, lm_y_l_f_w),
#     m_y_l_f = map(data, lm_y_l_f),
#     m_y_l = map(data, lm_y_l),
#     m_y = map(data, lm_y),
#     med_length_cm = map(
#       data,
#       ~ median(.x$length_cm, na.rm = TRUE)
#     ) %>% as.numeric(),
#     med_fat_pc = map(
#       data,
#       ~ median(.x$fat_pc, na.rm = TRUE)
#     ) %>% as.numeric(),
#     mean_length_cm = map(
#       data,
#       ~ mean(.x$length_cm, na.rm = TRUE)
#     ) %>% as.numeric(),
#     mean_fat_pc = map(
#       data,
#       ~ mean(.x$fat_pc, na.rm = TRUE)
#     ) %>% as.numeric(),
#     mean_year = map(
#       data,
#       ~ mean(.x$year, na.rm = TRUE)
#     ) %>% as.numeric(),
#         mean_value = map(
#       data,
#       ~ mean(.x$value, na.rm = TRUE)
#     ) %>% as.numeric()
#   ) %>% 
#   mutate(across(matches("m_"), ~ map(.x, AIC), .names = "{.col}_AIC")) %>% 
#   mutate(
#     glance = map(m_y_l_f_w, broom::glance),
#     year_pval = map(m_y_l_f_w, ~ broom::tidy(.x)[[2, 5]] %>% as.numeric()),
#     # tidy gets summary variables of the m1_y_l_f_w coefficients, pivot to get coeffs for unnest
#     tidy = map(m_y_l_f_w, ~ broom::tidy(.x) %>%
#       select(term, estimate) %>%
#       pivot_wider(names_from = "term", values_from = "estimate") %>%
#       clean_names() %>%
#       rename_with(.cols = everything(), .fn = ~ paste0(.x, "_coeff"))),
#     # augment gets per observation variables (e.g., residuals)
#     augment = map2(m_y_l_f_w, data, ~ broom::augment(.x, .y)),
#     partial_resids = map(m_y_l_f_w, ~ residuals(.x, type = "partial") %>%
#       as_tibble() %>%
#       rename_with(.cols = everything(), .fn = ~ paste0(.x, "_partial_resid"))),
#     normal_resids = map(m_y_l_f_w, ~ residuals(.x) %>%
#       as_tibble() %>%
#       rename_with(.cols = everything(), .fn = ~ paste0(.x, "_normal_resid")))
#   ) %>%
#   # add package-generated plots for an extra check
#   mutate(
#     visreg = map(
#       m_y_l_f_w,
#       ~ visreg(.x, "year", gg = TRUE, type = "conditional")
#     ),
#     effect_plot = map(
#       m_y_l_f_w,
#       ~ effect_plot(.x, pred = year, interval = TRUE, partial.residuals = TRUE)
#     ))

# tbl_all <- tbl_merge(map(selection_man$m1_y_l_f_w, ~ tbl_regression(.x) %>% add_glance_table()))

# full_raw_data %>% GGally::ggpairs()

  
```


# Regsubsets

```{r cleaning}
full_raw_data <- read_excel("data/20230424_nordsjoen_stepan.xlsx", skip = 1) %>%
  clean_names() %>%
  select(species, year, hel_vekt_g, length_cm, fettinnhold_percent, matches("w_w"), lsi_percent, alder_y) %>%
  drop_na(species, year) %>%
  mutate(across(.cols = matches("w_w"), .fn = ~ log10(as.numeric(.x) + 1))) %>%
  mutate(across(.cols = matches("length_cm|hel_vekt"), .fn = ~ log10(as.numeric(.x)))) %>%
  mutate(across(.cols = matches("fettinnhold_percent|year|hel_vekt_g|alder_y|lsi_percent"), .fn = ~ as.numeric(.x))) %>%
  rename_with(
    ~ str_replace_all(.x, c(
      "w_w" = "ww",
      "^s" = "",
      "fettinnhold_percent" = "fat_pc",
      "hel_vekt_g" = "weight",
      "lsi_percent" = "lsi_pc",
      "alder_y" = "age"
    )) %>%
      str_to_lower(),
    .cols = !matches("species")
  ) %>%
  # remove obs with no pop data
  filter(if_any(matches("ww"), ~ !is.na(.x))) %>%
  pivot_longer(cols = matches("ww"), names_to = "variable", values_to = "value")


# full linear regression model
lm_full <- function(in_dat) {
  lm(
    data = in_dat, formula = value ~ year + length_cm + fat_pc + weight + lsi_pc,
    na.action = na.exclude
  )
}

# conditional manual
selection_man <- full_raw_data %>%
  group_by(species, variable) %>%
  drop_na(value, year, length_cm, fat_pc, weight, lsi_pc) %>%
  group_by(species, variable) %>%
  nest() %>%
  mutate(
    best_subset = map(data, ~ {
      reg <- regsubsets(value ~ year + length_cm + fat_pc + weight + lsi_pc, data = .x, nbest = 3, nvmax = 7, force.in = c(1))
      summ <- summary(reg)
      cbind(summ$which, round(cbind(rsq = summ$rsq, adjr2 = summ$adjr2, cp = summ$cp, bic = summ$bic, aic = summ$aic, rss = summ$rss), 3)) %>% as_tibble()
    })
  ) %>%
  select(best_subset) %>%
  unnest(best_subset)
    
sel <- selection_man %>%
  group_by(species, variable) %>%
  arrange(bic, .by_group = TRUE) %>%
  filter(row_number() < 4) %>%
  mutate(across(.cols = matches("species|variable"), ~ as.factor(.x)))


  

sel_dummy <- sel%>% 
   pivot_longer(cols = c(species, variable),
              names_to = "dummy_names",
              values_to = "dummy_levels") %>% 
 mutate(dummy_value = 1) %>%
 pivot_wider(names_from = c(dummy_names, dummy_levels),
             values_from = dummy_value) %>% 
  mutate(
    across(everything(), ~replace_na(.x, 0))
  ) %>% select(-rsq, -adjr2, -cp, -bic, -rss)

res.pca <- prcomp(sel_dummy)
res.pca

fviz_pca_ind(res.pca)
    
fviz_pca_var(res.pca, col.var="steelblue")
fviz_pca_biplot(res.pca, label ="var")
fviz_pca_biplot(res.pca, geom = c("point","text"),
                addEllipses = TRUE, ggtheme = theme_gray(), alpha.var=0.3,
                col.var = "steelblue", repel=TRUE) 
sel_dummy %>% GGally::ggpairs()


  
regsubsets(data = full_raw_data %>%
  drop_na() , x= value ~ year + length_cm + fat_pc + weight + lsi_pc + age, nbest = 1, nvmax = 7, force.in = c(1)) %>% summary()


```


## Added-variable or partial regression plot TODO, outdated cleaning

See: https://stackoverflow.com/questions/59150905/is-there-a-ggplot2-analogue-to-the-avplots-function-in-r , https://bookdown.org/rwnahhas/RMPH/mlr-viz-adj.html
```{r}
# jtools::effect_plot(pop_lever)
# 
# 
# yz_lm <- function(df) {
#     lm(data = df, formula = value ~  hel_length_cm + fat_pc, na.action = na.exclude)
# }
# 
# xz_lm <- function(df) {
#     lm(data = df, formula = year ~  hel_length_cm + fat_pc, na.action = na.exclude)
# }
# 
# # exported .xlsx to .csv from the file received from Sylvia on mail 14/4/23 using Excel.
# # cleaning, removing unused variables
# pop_lever_added_var <- read_csv2("data/Hele datasettet lipidvekt til Sylvia med fys param sfr.csv") %>%
#   clean_names() %>%
#   select(year, area, species, hel_length_cm, fat_pc, matches("log.+ww")) %>%
#   filter(if_any(matches("log"), ~ !is.na(.x))) %>%
#   # pivoting to tidy data
#   pivot_longer(cols = matches("log.+ww"), names_to = "variable", values_to = "value") %>%
#   mutate(
#     year = as.integer(year)
#   ) %>%
#   # gjøre tidy
#   group_by(species, variable) %>%
#   nest() %>%
#   mutate(yz_model = map(data, yz_lm)) %>%
#   mutate(xz_model = map(data, xz_lm)) %>%
#   # glance gets the model summary variables
#   mutate(
#     # glance = map(model, broom::glance),
#     # # tidy gets summary variables of the model coefficients
#     # tidy = map(model, broom::tidy),
#     # augment gets per observation variables (e.g., residuals)
#     # augment = map2(model, data, ~ broom::augment(.x, .y)),
#     yz_resids = map2(yz_model, data, ~ (residuals(.x) + 
#                                           mean(.y$value, na.rm = TRUE) +
#                                           0
#                                         ) %>%
#       as_tibble() %>%
#       rename_with(.cols = everything(), .fn = ~ paste0(.x, "_yz_resids"))),
#      xz_resids = map2(xz_model, data, ~ (residuals(.x) + mean(.y$year)) %>%
#       as_tibble() %>%
#       rename_with(.cols = everything(), .fn = ~ paste0(.x, "_xz_resids"))),
#   ) %>% unnest(data, yz_resids , xz_resids)
# 
# pop_lever_added_var %>% 
#   ggplot(aes(value_xz_resids, value_yz_resids)) +
#   geom_jitter(size = 0.2) +
#   facet_grid(species ~ variable, scales = "free") +
#   theme_bw() +
#   theme(
#     axis.text.x = element_text(angle = 90, hjust = 1)
#   ) +
#   scale_x_continuous(breaks = pretty_breaks())+ylab("pop_lever_added_var")
# 
# # scatterplot
# pop_lever_added_var %>% 
#   ggplot(aes(year, value )) +
#   geom_jitter(size = 0.2) +
#   facet_grid(species ~ variable, scales = "free") +
#   theme_bw() +
#   theme(
#     axis.text.x = element_text(angle = 90, hjust = 1)
#   ) +
#   scale_x_continuous(breaks = pretty_breaks())+ylab("scatter")

```
